default_sqlite: &default_sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

default_postgres: &default_postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default_sqlite
  database: storage/development.sqlite3

test:
  <<: *default_sqlite
  database: storage/test.sqlite3

production:
  <<: *default_postgres
  url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *default_postgres
    url: <%= ENV['DATABASE_URL'] %>
